#!/bin/csh
# 
# This script scans the ALADDIN subroutines file for routines requiring
# five arguments. The names of these routines are extracted and used to
# create an if-then-else loop which uses an input character string to
# to decide which of these routines should be called. Presently the
# argument list used is the same for each. See also the subroutines
# contained in the file alev.f in the Aladdin distribution.
#
# This is the basic pattern to be used in generating the if-then-else loop;
# it is stored temporarily in the file "pattern".
#
cat > pattern <<EOF
      else if (leval == '#xxxx') then
         call xxxx(pet, fit_coef, num_fit_coef, pfit, kermsg)
EOF
#
# Use grep to search for all subroutine names in the ALADDIN subroutine
# file which have five arguments; write this list out to file "list".
#
grep -i "subroutine [a-z0-9]*([a-z]*, [a-z]*, [a-z]*, [a-z]*, [a-z]*)" aladdin_subr.F > list
#
# Strip off stuff before & after subroutine name
#
tedi list <<EOF
dp1,];      SUBROUTINE 
dap1,];(
dp1,];(
end 
EOF
#
# For each routine name in "list", replace the "xxxx" in the if-then-else
# pattern with the routine name, but do this in a separate file, "alsubcall".
#
foreach subname (`cat list`)
#
tedi alsubcall <<EOF
cfa1,2,];pattern
rp.-1,];xxxx;$subname
end
EOF
#
end
#
# Remove temporary files
#
rm list pattern


