import matplotlib.pyplot as plt
import numpy as np
from polygon import *
import sys
from importlib import reload

def write_cylinder_dg2d_input(R_tot,NR,material,Ntheta_min=12,Ntheta_max=200,wallfile_name="wallfile.txt",dg2dfile_name="dg2d.in",recyc=1.0):
    Xmin = -1.5*R_tot
    Xmax = 1.5*R_tot
    Zmin = -1.5*R_tot
    Zmax = 1.5*R_tot

    delta_r = 2*R_tot/(1.0+2*NR)
    r_grid = np.linspace(0.0,R_tot-0.5*delta_r,num=NR)


    plasma_polys = []

    # First polygon (0) is simple: a polygon with Ntheta_min sides. 
    #    Corresponds to the center of the plasma  at rgrid[0]=0.0 
    # Next (1:NR) polygons are the "main" plasma ones. Consists of a cresent-shaped polygon,
    #    leaving a small quadrilateral, which gets defined next. This is necessary because
    #    polygons with holes is not supported.
    # Next (NR:2*NR-1) are the "fillers". Statistics from these will not be reported.
    # Finally, (2*NR:2*NR+1) are the wall polygons

    # ith polygon has Ntheta_min*(r_grid[i]+0.5*delta_r)/(0.5*delta_r) nodes sides
    Ntheta = ( Ntheta_min*(r_grid+0.5*delta_r/(0.5*delta_r)) ).astype(int)

    # Gets the wall id (counting from 1) of a node based on its global index (counting from 0)
    def get_node_wall_id(node_id):
        wall_id = -1

        n_node = 0
        for i in range(0,NR):
            if node_id >= n_node and node_id < n_node+Ntheta[i]:
                wall_id = i+1
            n_node += Ntheta[i]

        if wall_id < 1:
            sys.exit("ERROR: index algebra failed in get_node_wall_id; node_id = $d, wall_id = $d"%(node_id,wall_id))
        return wall_id

    def get_node_wall_ids_from_global_index(i):
        wall_id = -1
        node_id = -1

        n_node = 0
        for i in range(0,NR):
            if i >= n_node and i < n_node+Ntheta[i]:
                wall_id = i+1
                node_id = i - n_node
            n_node += Ntheta[i]

        if wall_id < 1 or node_id < 0
            sys.exit("ERROR: index algebra failed in get_node_wall_ids_from_global_index; i = $d"%(i))
        return wall_id, node_id

    ####################################################
    # Define surfaces (for "wallfile")
    surfs = []
    for i in range(0,NR):
        r = delta_r * (i + 0.5)
        dtheta = 2.0*pi/Ntheta[i]
        theta = np.linspace(0.0,2.0*pi,num=Ntheta[i],endpoint=False)
        
        # By convention (which is relied upon later in this function), 
        #  start with the leftmost point and go counter-clockwise
        x = -r*np.cos(theta)
        z = -r*np.sin(theta)

        # In dg2d, walls are counted from 1, but nodes within them are counted from 0
        surfs.append(Surface(i+1))

        inode = 0
        # Now build the nodes
        for j in range(0,Ntheta[i]):
            node = Vertex(inode,x[j],z[j])
            inode+=1
            surfs[-1].add_vertex(node)

    ####################################################
    # Write wallfile using the defined surfaces
    wallfile = open(wallfile_name,"w")
    wallfile.write("# Wallfile automatically generated by script\n")
    wallfile.write("%d\n"%(NR))
    wallfile.write("#\n"%(NR))
    for i in range(0,NR):
        wallfile.write("%d"%Ntheta[i])
    wallfile.write("\n#\n")
    for i in range(0,NR):
        wallfile.write("# coordinates for wall %d - %d points\n"%(i+1,Ntheta[i]))
        for j in range(0,Ntheta[i]):
            x = surfs[i].vertices[j].coords[0]
            z = surfs[i].vertices[j].coords[1]
            wallfile.write("%f %f\n"%(x,z))
    wallfile.close()

    ####################################################
    # Build polygons from wallfile nodes
    polys = []
     
    # First polygon is straightforward
    # Next (NR-1) polygons are the "main" cresent-shaped ones that exclude a small quadrilateral on the left side
    for isurf in range(0,NR):
        polys.append(Polygon())
        for j in range(0,Ntheta[isurf]):
            polys[-1].add_vertex(surfs[isurf].vertices[j])
        # Now go backwards along previous surface
        if isurf > 0:
            for j in range(Ntheta[isurf-1]-1,-1,-1):  # Too many "-1"s!
                polys[-1].add_vertex(surfs[isurf-1].vertices[j]
        # Just to make sure everything is ok, add the first point again. dg2d is fine with this.
        polys[-1].add_vertex(surfs[isurf].vertices[0])

    # Now make the little quadrilaterals to close the surface
    for isurf in range(1,NR):
        polys.append[Polygon()]
        polys[-1].add_vertex(surfs[isurf-1].vertices[0])
        polys[-1].add_vertex(surfs[isurf-1].vertices[-1])
        polys[-1].add_vertex(surfs[isurf].vertices[-1])
        polys[-1].add_vertex(surfs[isurf].vertices[0])

    ####################################################
    # Write dg2d input file
    dg2dfile = open(dg2dfile_name,"w")

    for ipoly in range(0,len(polys)):
        if ipoly < NR:
            wallid = ipoly
        else:
            wallid = ipoly - NR + 2
        polys[ipoly].write_plasma_polygon_dg2d(dg2dfile,stratum=ipoly+1,wallid=wallid,commonzone=True)

    wallnodes = surfs[-1].vertices

    def close_in_universal_cell(f,wallnodes,wallid,stratum,material,recyc):

    # Syntax is a little confusing right now. "wallid" in this routine actually assumes 
    # they're counted from zero and corrects to write dg2d input file
    Polygon.close_in_universal_cell(dg2dfile,wallnodes,NR-1,NR-1,2*NR,material,recyc):
    dg2dfile.close()

    return rgrid

def write_dg2d_input_from_triangle_file(trifile_base,material,recyc,dg2dfile_name="dg2d.in",polygon_filename="polygons.nc",debug=False,trust_wallflags=True):

    def next_noncomment_line(f):
        found=False
        while not found:
            line = f.readline().strip()
            if not (line[0] == '#' or line[0:2] == "//"):
                found = True
        return line

    nodefile = open(trifile_base+".node",'r')
    line1 = next_noncomment_line(nodefile).split(",")
    nnode = int(line1[0])
    nattr = int(line1[2])

    node_coords = np.zeros([nnode,2])
    Te_node = np.zeros([nnode])
    Ti_node = np.zeros([nnode])
    ne_node = np.zeros([nnode])
    mach_node = np.zeros([nnode])
    Br_node = np.zeros([nnode])
    Bphi_node = np.zeros([nnode])
    Bz_node = np.zeros([nnode])
    wallflag_node = np.zeros([nnode],dtype=int)
    lowestRnode = 0
    Rmin = -1.0
    Rmax = -1.0
    Zmin = 99999.0
    Zmax = -99999.0
    nnode_read=0
    vertices = []
    wallvertices = []
    while nnode_read < nnode:
        line = next_noncomment_line(nodefile).split(",")
        inode = int(line[0])
        node_coords[inode,0] = float(line[1])
        node_coords[inode,1] = float(line[2])
        Te_node[inode] = 1.602e-19*float(line[3])
        Ti_node[inode] = 1.602e-19*float(line[4])
        ne_node[inode] = float(line[5])
        mach_node[inode] = float(line[6])
        Br_node[inode] = float(line[7])
        Bphi_node[inode] = float(line[8])
        Bz_node[inode] = float(line[9])
        wallflag_node[inode] = int(line[10])

        vertices.append(Vertex(inode,node_coords[inode,0],node_coords[inode,1]))

        if not trust_wallflags:
            vertices[-1].wall = False  # Using invalid triangles later to add wall nodes
        elif wallflag_node[inode] == 1:
            vertices[-1].wall = True
            wallvertices.append(vertices[-1])
            wallvertices[-1].id = vertices[-1].id
        nnode_read += 1

    nodefile.close()

    elefile = open(trifile_base+".ele",'r')
    line1 = next_noncomment_line(elefile).split(",")
    ntri = int(line1[0])
    nattr = int(line1[2])

    trinodes = np.zeros([ntri,3],dtype=int)
    Te_tri = np.zeros([ntri])
    Ti_tri = np.zeros([ntri])
    ne_tri = np.zeros([ntri])
    mach_tri = np.zeros([ntri])
    Br_tri = np.zeros([ntri])
    Bphi_tri = np.zeros([ntri])
    Bz_tri = np.zeros([ntri])
    validflag = np.zeros([ntri],dtype=int)
    lowestRtri = -1
    ntri_read=0
    polys = []
    wallpolys = []
    invalidpolys = []
    iline = 0
    while iline < ntri:
        line = next_noncomment_line(elefile).split(",")
        itri = int(line[0])
        trinodes[itri,0] = int(line[1])
        trinodes[itri,1] = int(line[2])
        trinodes[itri,2] = int(line[3])
        Te_tri[itri] = 1.602e-19*float(line[4])
        Ti_tri[itri] = 1.602e-19*float(line[5])
        ne_tri[itri] = float(line[6])
        mach_tri[itri] = float(line[7])
        Br_tri[itri] = float(line[8])
        Bphi_tri[itri] = float(line[9])
        Bz_tri[itri] = float(line[10])
        validflag[itri] = int(line[11])
    
        if (validflag[itri] == 0):
            invalidpolys.append(Polygon())
            invalidpolys[-1].id = itri
            invalidpolys[-1].add_vertex(vertices[trinodes[itri,0]])
            invalidpolys[-1].add_vertex(vertices[trinodes[itri,1]])
            invalidpolys[-1].add_vertex(vertices[trinodes[itri,2]])
        else:
            polys.append(Polygon())
            polys[-1].id = itri
            polys[-1].add_vertex(vertices[trinodes[itri,0]])
            polys[-1].add_vertex(vertices[trinodes[itri,1]])
            polys[-1].add_vertex(vertices[trinodes[itri,2]])
   
        iline += 1
    elefile.close()
    ntri = len(polys)

    if not trust_wallflags:
#        wallvertices = infer_wall_nodes(polys,invalidpolys)
        vertices = purge_invalid_nodes(vertices,polys)
        wallvertices = infer_wall_nodes(polys,invalidpolys)

    # Now that we know the wall vertices for sure, 
    # go back and calculate some needed things:
    rtemp = []
    ztemp = []
    for node in vertices:
        if node in wallvertices:
            node.wall = True

#            print("wallnode id = %d"%node.id)

            if node.coords[0] < Rmin or Rmin < 0.0:
                Rmin= node.coords[0]
                lowestRnode = node
            if node.coords[0] > Rmax:
                Rmax= node.coords[0]
            if node.coords[1] < Zmin:
                Zmin= node.coords[1]
            if node.coords[1] > Zmax:
                Zmax= node.coords[1]

    #plt.plot(rtemp,ztemp,".")
    #plt.plot(lowestRnode.coords[0],lowestRnode.coords[1],"o")
    #plt.savefig("test.png")
    #plt.close()

    Zmin_tot = Zmin - (Zmax-Zmin)
    Zmax_tot = Zmax + (Zmax-Zmin)
    Rmax_tot = 1.5*Rmax
    Rmin_tot = max(0.0001,0.5*Rmin)

    for tri in polys:
        nwallnodes = tri.reorder_wallnodes_first()
        if nwallnodes >= 2:
            tri.alongwall = True
            wallpolys.append(tri)
#            print("wallpoly.id = %d"%wallpolys[-1].id)
    print("Number of wall triangles= %d"%len(wallpolys))

    dg2dfile = open(dg2dfile_name,'w')
    dg2dfile.write("symmtry cylindrical\n")
    dg2dfile.write("bounds "+str(Rmin_tot)+" "+str(Rmax_tot)+" "+\
            str(Zmin_tot)+" "+str(Zmax_tot)+"\n")
    dg2dfile.write("wallfile wallfile.txt\n")
    dg2dfile.write("end_prep\n\n")

    for poly in polys:
        poly.write_plasma_polygon_dg2d(dg2dfile,stratum=poly.id+1,wallid=1,debug=debug)

    wallvertices_ordered = []
    wallvertices_ordered.append(lowestRnode)

    for i in range(0,len(wallvertices)-1):
        if i==0:
            prevnode = lowestRnode
        else:
            prevnode = wallvertices_ordered[i-1]

#        next_node = find_next_wall_node(wallvertices_ordered[i],prevnode,wallvertices,wallpolys,i==0)
#        if i == 85:
        if False:
            rtemp = []
            ztemp = []
            for node in wallvertices_ordered:
                rtemp.append(node.coords[0])
                ztemp.append(node.coords[1])
            plt.plot(rtemp,ztemp,"-")
            plt.plot(rtemp,ztemp,"-")
            rtemp = []
            ztemp = []
            for node in vertices:
                rtemp.append(node.coords[0])
                ztemp.append(node.coords[1])
            plt.plot(rtemp,ztemp,".")
            plt.xlim([1.3,1.5])
            plt.ylim([-1.2,-0.5])
            plt.savefig("test.png")
            plt.close()
        next_node = find_next_wall_node(wallvertices_ordered[i],prevnode,vertices,polys,i==0)
        wallvertices_ordered.append(next_node)

    # wallvertices_ordered is now the list of wall vertices, starting at 
    # the minimum R value, and going around counter-clockwise

    # Enclose in universal cell
    # TODO: Fix this routine so that big polygon doesn't wrap back to its own point.
    Polygon.close_in_universal_cell(dg2dfile,wallvertices_ordered,lowestRnode,0,ntri+1,material,recyc)

    dg2dfile.write("polygon_nc_file polygon.nc\n")
    dg2dfile.write("end")
    dg2dfile.close()

    return polys

def write_dg2d_input_from_single_wall(wallfile_name,material,recyc,walltemp=300.0,minarea=-1.0,dg2dfile_name="dg2d.in",polygon_filename="polygons.nc",debug=False,exitnodes=[]):

    # Read the wallfile
    wallfile = open(wallfile_name,'r')

    def next_noncomment_line(f):
        found=False
        while not found:
            line = wallfile.readline().strip()
            if not line[0] == '#':
                found = True
        return line

    # This function only cares about the first wall
    nwalls = int(next_noncomment_line(wallfile))
    line = next_noncomment_line(wallfile).split()

    npoints = int(line[0])
    npoints_sep = int(line[1])

    nlines = npoints
    iwall = 0
    ipoint = 0
    Rcoords = []
    Zcoords = []
    wall = Surface(0)
    for ipoint in range(0,npoints):
        line = next_noncomment_line(wallfile)
        line_floats = [float(n) for n in line.split()]
        Rcoord = line_floats[0]
        Zcoord = line_floats[1]
        Rcoords.append(Rcoord)
        Zcoords.append(Zcoord)
        wall.add_vertex(Vertex(ipoint,Rcoord,Zcoord))

    sep = Surface(1)
    Rcoords_sep = []
    Zcoords_sep = []
    for ipoint in range(0,npoints_sep):
        line = next_noncomment_line(wallfile)
        line_floats = [float(n) for n in line.split()]
        Rcoord = line_floats[0]
        Zcoord = line_floats[1]
        Rcoords_sep.append(Rcoord)
        Zcoords_sep.append(Zcoord)
     
    # Now we have read the wallfile. We know how many points are in each wall and the R/Z coordinates for each point defining these walls. We can close the wallfile now.
    wallfile.close()

    clockwise = False

    polys=[]

    # There will be only three polygons:
    # 1: the vacuum vessel interior
    # 2: Small polygon representing exit on LFS, connects to right side of universal cell
    # 3: Most of the wall to the edge of the universal cell. Shares zone with #2. 

    # Polygon 1
    poly = Polygon()
    poly.add_whole_surface(wall,backward=True)
    
    # Now we build the wall specification in the dg2d input file
    dg2dfile = open(dg2dfile_name,'w')

    ####################################
    # First, set the header
    dg2dfile.write("symmetry cylindrical\n")

    ####################################
    # Find and write appropriate bounds
    #Rcoords = walls[0].vertices[:].coords[0]
    #Zcoords = walls[0].vertices[:].coords[1]
    Rrange = np.amax(Rcoords) - np.amin(Rcoords)
    Zrange = np.amax(Zcoords) - np.amin(Zcoords)
    Zmin = np.amin(Zcoords) - Zrange
    Zmax = np.amax(Zcoords) + Zrange
#    Rmin = max(np.amin(Rcoords) - 0.8*Rrange, 0.2*np.amin(Rcoords))
    Rmin = 0.0001
    Rmax = np.amax(Rcoords) + Rrange
    dg2dfile.write("bounds     %f %f    %f %f \n" % (Rmin, Rmax, Zmin, Zmax))

    ####################################
    # Write out name of wallfile
    dg2dfile.write("wallfile "+wallfile_name.strip()+"\n")

    dg2dfile.write("end_prep\n")
    dg2dfile.write("\n")

    poly.write_plasma_polygon_dg2d(dg2dfile,minarea=minarea,wallid=1,debug=debug)

    if exitnodes == []:
        wall.write_solid_polygon_dg2d(2,dg2dfile,material,recyc,walltemp,debug=debug)
    else:
        wall.write_solid_polygon_with_exit(2,dg2dfile,exitnodes,material,recyc,walltemp,debug=debug)

    dg2dfile.write("polygon_nc_file "+polygon_filename+"\n")

    if debug:
        dg2dfile.write("quit\n")

    dg2dfile.write("end\n")

    dg2dfile.close()

    Polygon.clear_numPolygon()

    return polys,wall, Rcoords_sep, Zcoords_sep

def write_dg2d_input_from_wallfile(wallfile_name,topology,topology_params,material,recyc,dg2dfile_name="dg2d.in",polygon_filename="polygons.nc",debug=False):

    # Read the wallfile
    wallfile = open(wallfile_name,'r')

    def next_noncomment_line(f):
        found=False
        while not found:
            line = wallfile.readline().strip()
            if not line[0] == '#':
                found = True
        return line

    # Get the number of points defining each wall (npoints) 
    # from the next one-to-several lines
    nwalls = int(next_noncomment_line(wallfile))
    npoints = [0]*nwalls
    nwalls_read=0
    while nwalls_read < nwalls:
        line = next_noncomment_line(wallfile)
        npoints_list = [int(n) for n in line.split()]
        nwalls_current = len(npoints_list)
        npoints[nwalls_read:nwalls_read+nwalls_current] = npoints_list
        nwalls_read += nwalls_current

    nlines = sum(npoints)
    iwall = 0
    ipoint = 0
    walls = []
    Rcoords = []
    Zcoords = []
    for iwall in range(0,nwalls):
        walls.append(Surface(iwall))
        for ipoint in range(0,npoints[iwall]):
            line = next_noncomment_line(wallfile)
            line_floats = [float(n) for n in line.split()]
            Rcoord = line_floats[0]
            Zcoord = line_floats[1]
            Rcoords.append(Rcoord)
            Zcoords.append(Zcoord)
            walls[iwall].add_vertex(WallVertex(iwall,ipoint,Rcoord,Zcoord))

    # Now we have read the wallfile. We know how many points are in each wall and the R/Z coordinates for each point defining these walls. We can close the wallfile now.
    wallfile.close()

    if topology == "LTX":
        # For LTX, the walls should be defined in the following order:
        # 1: External solid wall
        # 2: Several closed flux surfaces, starting from the outermost
        num_closed_surfaces = topology_params[0]
        # 3: The remainder are open flux surfaces (outside the limiter), starting with the outermost
        num_open_surfaces = nwalls-1-num_closed_surfaces

        clockwise = False

        # The vertex indices of the solid wall which correspond to the limiter edges.
        # MUST go from top to bottom (high to low index, when listed counterclockwise)
        limiter_vertex_idx = [topology_params[1], topology_params[2]]

        # Important to do the lower one first so that indices are preserved after inserting
        limlcfs_idx_lower = walls[1].insert_vertex_into_surface(walls[0].vertices[limiter_vertex_idx[1]])
        limlcfs_idx_upper = walls[1].insert_vertex_into_surface(walls[0].vertices[limiter_vertex_idx[0]])

        polys=[]

        ############
        # First, define the closed flux surface zones
        for isurf in range(1,num_closed_surfaces):
            outer = walls[isurf]
            inner = walls[isurf+1]
            small, large= Surface.genpolys_from_two_closed_surfs(inner,outer)
            polys.append( Polygon() )
            polys[-1].vertices = copy.deepcopy(small.vertices)
            polys.append( Polygon() )
            polys[-1].vertices = copy.deepcopy(large.vertices)

        polys.append(Polygon())
        polys[-1].add_whole_surface(walls[num_closed_surfaces],backward=True)
        polys[-1].add_vertex(walls[num_closed_surfaces].vertices[-1])
    
        ############
        # Then, the limiter region beyond the LCFS
        polys.append(Polygon())
        # The relevant part of the solid wall
        for vertex in walls[0].vertices[limiter_vertex_idx[1]::-1]:
            polys[-1].add_vertex(vertex)
        for vertex in walls[0].vertices[-1:limiter_vertex_idx[0]-1:-1]:
            polys[-1].add_vertex(vertex)
        # The relevant part of the LCFS
        for vertex in walls[1].vertices[limlcfs_idx_upper:]:
            polys[-1].add_vertex(vertex)
        for vertex in walls[1].vertices[0:limlcfs_idx_lower+1]:
            polys[-1].add_vertex(vertex)

        if num_open_surfaces == 0:
            # Case where the scrape off layer is all one polygon
            polys.append(Polygon())

            # The relevant part of the LCFS
            for vertex in walls[1].vertices[limlcfs_idx_lower:limlcfs_idx_upper+1]:
                polys[-1].add_vertex(vertex)

            # Add relevant part of solid wall
            for vertex in walls[0].vertices[limiter_vertex_idx[0]-1:limiter_vertex_idx[1]:-1]:
                polys[-1].add_vertex(vertex)
 
            polys[-1].add_vertex(walls[1].vertices[limlcfs_idx_lower])
        else:
            ############
            # Then, the zone between the LCFS and the first open flux surface (last in the list of walls)
            polys.append(Polygon())
    
            # The relevant part of the LCFS
            for vertex in walls[1].vertices[limlcfs_idx_lower:limlcfs_idx_upper+1]:
                polys[-1].add_vertex(vertex)
            # Now, find the solid wall index corresponding to the ends of the first open flux surfaces
    
            # First build a dummy polygon to track other surface
            dummyPoly = Polygon(increment=False)
            for vertex in walls[-1].vertices[-1::-1]:
                dummyPoly.add_vertex(vertex)
            wallidx_intersect_upper = dummyPoly.get_next_vertex_extrapolated_to_wall(walls[0])
            dummyPoly = Polygon(increment=False)
            for vertex in walls[-1].vertices:
                dummyPoly.add_vertex(vertex)
            wallidx_intersect_lower = dummyPoly.get_next_vertex_extrapolated_to_wall(walls[0])
    
            # Add relevant part of upper solid wall
            for vertex in walls[0].vertices[limiter_vertex_idx[0]:wallidx_intersect_upper-1:-1]:
                polys[-1].add_vertex(vertex)
    
            # Add first open flux surface
            for vertex in walls[-1].vertices:
                polys[-1].add_vertex(vertex)
    
            # Add relevant part of lower solid wall
            for vertex in walls[0].vertices[wallidx_intersect_lower:limiter_vertex_idx[1]-1:-1]:
                polys[-1].add_vertex(vertex)
    
            # Close the polygon
            polys[-1].add_vertex(walls[1].vertices[limlcfs_idx_lower])
    
            ############
            # Then, the zone between the outermost flux surface and the solid wall. Similar to above
            polys.append(Polygon())
            polys[-1].vertices = copy.deepcopy(Surface.genpoly_from_rightwall_and_surface(walls[0],walls[num_closed_surfaces+1]).vertices)

    
            ############
            # Finally, the zones bounded by open flux surfaces and solid wall
    
            for isurf in range(0,num_open_surfaces-1):
    
                polys.append( Polygon() )
    
                outer = walls[num_closed_surfaces + 1 + isurf]
                inner = walls[num_closed_surfaces + 1 + isurf + 1]
    
                polys[-1].vertices = copy.deepcopy(Surface.genpoly_from_two_open_surfs(inner,outer,walls[0]).vertices)
    
    # Don't think we need polygon-to-surface mapping anymore. Commenting out for now. 
    # If this is brought back, above logic needs to respected
#        poly_to_surf_map = []
#        # The polygons bounded by two closed flux surfaces (two polygons each):
#        for isurf in range(1,num_closed_surfaces):
#            poly_to_surf_map.append([isurf,isurf+1])
#            poly_to_surf_map.append([isurf,isurf+1])
#
#        # The innermost closed flux surface defines a single polygon
#        poly_to_surf_map.append([num_closed_surfaces,num_closed_surfaces])
#
#        # The limiter region
#        poly_to_surf_map.append([1,nwalls-1])
#
#        # The innermost open region
#        poly_to_surf_map.append([1,nwalls-1])
#
#        # The outermost open region
#        poly_to_surf_map.append([num_closed_surfaces+1,num_closed_surfaces+1])
#
#        for isurf in range(num_closed_surfaces+1,nwalls-1):
#            poly_to_surf_map.append([isurf,isurf+1])
#
#        if len(poly_to_surf_map) != len(polys):
#            print("ERROR: poly_to_surf_map does not have the same elements as polys")
#            print("len(polys)="+str(len(polys))+"\nlen(poly_to_surf_map)="+str(len(poly_to_surf_map)))
#            sys.exit(1)
#
    else:
        print("Error: topology "+topology+" not defined.")
        sys.exit(0)

    # Now we build the wall specification in the dg2d input file
    dg2dfile = open(dg2dfile_name,'w')

    ####################################
    # First, set the header
    dg2dfile.write("symmetry cylindrical\n")

    ####################################
    # Find and write appropriate bounds
    #Rcoords = walls[0].vertices[:].coords[0]
    #Zcoords = walls[0].vertices[:].coords[1]
    Rrange = np.amax(Rcoords) - np.amin(Rcoords)
    Zrange = np.amax(Zcoords) - np.amin(Zcoords)
    Zmin = np.amin(Zcoords) - Zrange
    Zmax = np.amax(Zcoords) + Zrange
#    Rmin = max(np.amin(Rcoords) - 0.8*Rrange, 0.2*np.amin(Rcoords))
    Rmin = 0.0001
    Rmax = np.amax(Rcoords) + Rrange
    dg2dfile.write("bounds     %f %f    %f %f \n" % (Rmin, Rmax, Zmin, Zmax))

    ####################################
    # Write out name of wallfile
    dg2dfile.write("wallfile "+wallfile_name.strip()+"\n")

    dg2dfile.write("end_prep\n")
    dg2dfile.write("\n")

 
    for poly in polys:
        poly.write_plasma_polygon_dg2d(dg2dfile,wallid=1,commonzone=True,debug=debug)

    walls[0].write_solid_polygon_dg2d(len(polys)+1,dg2dfile,material,recyc,debug)
    dummyPoly=Polygon()
    dummyPoly=Polygon()

    dg2dfile.write("polygon_nc_file "+polygon_filename+"\n")

    if debug:
        dg2dfile.write("quit\n")

    dg2dfile.write("end\n")

    dg2dfile.close()

    Polygon.clear_numPolygon()

    return polys,walls

    # No longer needs to return this stuff for defineback to work properly
#    return polys, walls, poly_to_surf_map

def plot_polygon_from_file(ipoly):
    polyfilename="poly."+str(ipoly)+".dat"
    polyfile = open(polyfilename,'r')
    first = True
    R=[]
    Z=[]
    for line in polyfile:
        strdata=line.split()
        if first:
            first = False
        else:
            R.append(float(strdata[0]))
            Z.append(float(strdata[1]))

    # Make sure polygon is closed
    R.append(R[0])
    Z.append(Z[0])

    plt.plot(R,Z,"-+")

def plot_allpolys_from_file(N):
    plt.clf()
    for ipoly in range(1,N+1):
        plot_polygon_from_file(ipoly)


