(defun fixit ()
  "Change C-style array references to Fortran-style"
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward ")(\\|)\n     &" nil t)
      (uncontinue-line)
      (while (re-search-forward ")(" nil t)
        (backward-char 1)
        (let ((x (point))
              (s))
          (forward-sexp 1)
          (setq s (buffer-substring x (point)))
          (delete-region x (point))
          (backward-sexp 1)
          (insert s)
          (backward-char 1)
          (delete-char 2)
          (insert ",")))
      (continue-line))))

(defun fixit-and-save ()
  (fixit)
  (save-buffer))

(defun uncontinue-line ()
  (re-search-backward "^      ")
  (narrow-to-region (point)
                    (progn (forward-char 6)
			   (re-search-forward "^\\(      \\|[cC*]\\)")
                           (beginning-of-line) (point)))
  (goto-char (point-min))
  (while (re-search-forward "\n     &" nil t)
    (replace-match ""))
  (goto-char (point-min)))

(defun continue-line ()
  (goto-char (point-min))
  (while (> (- (point-max) (point)) 73)
    (forward-char 72)
    (insert "\n     &")
    (beginning-of-line))
  (goto-char (point-max))
  (widen))
             
